### ISSUE TITLE
Link in readme no longer works

### ISSUE THREAD

**Issue by mkeedlinger** [euank/node-image-dedupe#3]
The link provided no longer seems to work ([link to link](https://github.com/euank/node-image-dedupe/blob/96df6a3107cafdbe41dce326b70074bd40d6f9d2/README.md))

**Comment by euank** [comment]
Should be back up give or take a DNS record propagation.

I also updated the readme a little. Sorry for taking so long to get to this. Feel free to re-open this issue if you still have an issue accessing it after waiting a suitable time for a dns change.
